spring:
  profiles:
    include: secret, local
#  jackson.serialization.fail-on-empty.beans: false

#management:
#  metrics:
#    tags:
#      application: trigo
#  endpoints:
#    web:
#      exposure:
#        include: "*"