spring:
  application:
    name: trigo

  profiles:
    include: secret

  datasource:
    url: jdbc:mysql://host.docker.internal:3306/trigo?allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: trigo1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
        format-sql: true

  logging:
    level:
      org.springframework: DEBUG

server:
  port: 8081